### ISSUE TITLE
Keep Events beside Calendar Menu not working

### ISSUE THREAD

**Issue by cosmin-craciun** [Selenium-H/Notification-Center#31]
Using Pop!_OS 20.04 with pop-shell enabled. I have tried disabling / enabling the extension as well as completely removing it and adding it again. That option does not work, notifications remain next to calendar.

Edit : It appears to be caused by removing either of the default notification options, i.e Media Section, Events list, Notification list. If either one of those is set to "Don't show", the events come back besides the Calendar Menu

**Comment by Selenium-H** [comment]
Hi @cosmin-craciun, Does `Show Events List on Notification Center`, `Show Media Section on Notification Center`, `Show Notifications List on Notification Center`  options have any two or all three set as same position ( except `Don't Show`) ?

Please try disabling all other extensions and enabling just this one to see if it works. 
Also try resetting the extension. Reset button is present in `About` tab in extension preferences. 

I tried the extension on Pop!_OS 20.04 with pop-shell enabled and its working fine.

**Comment by cosmin-craciun** [comment]
> Hi @cosmin-craciun, Does `Show Events List on Notification Center`, `Show Media Section on Notification Center`, `Show Notifications List on Notification Center` options have any two or all three set as same position ( except `Don't Show`) ?
> 
> Please try disabling all other extensions and enabling just this one to see if it works.
> Also try resetting the extension. Reset button is present in `About` tab in extension preferences.
> 
> I tried the extension on Pop!_OS 20.04 with pop-shell enabled and its working fine.

Perhaps I misunderstood how this extension should function, in which case I apologise. However, here are my results. I tested with a fresh install of Pop!_OS 20.04 in a virtual machine, having only done the initial upgrades and instalation of the gnome extensions firefox extension.

These, along with 'AutoHide notification indicator in the panel' being set to No, are the options I set:

![image](https://user-images.githubusercontent.com/64773781/81189249-0eea8f00-8fbf-11ea-8f04-8d034759e712.png)

And this is the result I get when pressing the Calendar Menu:

![image](https://user-images.githubusercontent.com/64773781/81189432-38a3b600-8fbf-11ea-9b24-6d97317eb94e.png)


As you can clearly see, if either of the options I mentioned previously is set to 'Don't Show', the Calendar Menu reverts back to having a Notification Area inside itself, as well as the indicator being in the top right.

Now, what I am uncertain of, and I do hope you could help me clarify, if this is a normal behaviour I should expect. I tested with media being played, to see if the 'Media Section' category would only appear in the indicator provided by Notification Center or if it would also be present in the Calendar Menu area. I found that if media is being played, if the category 'Show Media Section' is set to 'Don't Show' in Notification Center, the notification for it appears under the Calendar Menu area, and does not appear under Notification Center.

With that being said, I do believe there either was something wrong with my testing, which I doubt considering that they were done on a completely fresh install inside a VM, or the bug is present as I have previously described it.

**Comment by Selenium-H** [comment]
Thanks for clearly explaining the issue.

The space beside `Calendar` menu `( messageList )` is shown whenever it holds either `Notification Section` or `Media Section` or `Events Section`.  By default it holds all of them and hence the empty space is present which is normal. 
With this extension enabled when `Keep events besides Calendar Menu` option is enabled the space beside `Calendar` menu still holds the `Events Section` hence the empty space is present. ( Which is filled when events are present or clicked on a date having events ). As you tested disabling this option don't show any events beside `Calendar` menu. (even when clicked on any dates having events on `Calendar` menu).

> Now, what I am uncertain of, and I do hope you could help me clarify, if this is a normal behaviour I should expect. I tested with media being played, to see if the 'Media Section' category would only appear in the indicator provided by Notification Center or if it would also be present in the Calendar Menu area. I found that if media is being played, if the category 'Show Media Section' is set to 'Don't Show' in Notification Center, the notification for it appears under the Calendar Menu area, and does not appear under Notification Center.

It's normal. When all the three sections are moved to `Notification Center` and  `Keep events besides Calendar Menu` option is disabled, the space beside the `Calendar` menu doesn't hold anything and hence it disappears. 
On setting any of three options, `Show Events List on Notification Center`, `Show Media Section on Notification Center`, `Show Notifications List on Notification Center` to `Don't Show`, that particular section is not moved to `Notification Center` and hence it remains beside `Calendar` menu and the empty space is shown since it holds that section which is not moved. 
In your testing  `Show Media Section on Notification Center` option was set to `Don't Show` Hence the space beside `Calendar` menu held `Media Section` and the empty space was present which was used for media notifications.

**Comment by cosmin-craciun** [comment]
@Selenium-H I understand now. I wasn't 100% sure as to how this extension functions, but now I see that what is happening is normal and intended behaviour. Thank you for taking the time to explain. Is it perhaps possible that my initial idea for the feature could be implemented somehow?

**Comment by Selenium-H** [comment]
Sorry for the delay. With the last commit in  [experimental](https://github.com/Selenium-H/Notification-Center/tree/experimental) `branch`, the empty space beside the calendar can be now hidden if `events section` is completely moved to `Notification Center`. It will reappear automatically if any section not in `Notification Center` receive any message.
