### ISSUE TITLE
Events and world clocks reappear after hiding

### ISSUE THREAD

**Issue by aunetx** [Selenium-H/Notification-Center#49]
Hi, thanks a lot for this extension!

I noticed some issues: the "events" sections is nearly never hidden from the calendar popup, and the clock section also reappears randomly.

Using Gnome 40 and last version from github :)

**Comment by Selenium-H** [comment]
Hi @aunetx, if you're using GNOME in a language other than `English` and this issue was appearing, it's fixed with last commit in [master](https://github.com/Selenium-H/Notification-Center/tree/master) `branch` 
In case the issue is present while using GNOME in `English`, could you please let me know the `preferences` under which it is happening?

**Comment by aunetx** [comment]
I was using French so I guess this was fixed! Thanks a lot :)

BTW, I'm the maintainer or another extension (Blur my Shell) and I really like this extension (aside with App-Grid-Tweaks), do you think you need help to maintain these two?

**Comment by Selenium-H** [comment]
Thanks! for your interest in these projects. However, currently it's fine with me maintaining them :)

**Comment by aunetx** [comment]
Ok cool then! If you need help for anything, don't hesitate
